### ISSUE TITLE
Create Job and create team buttons (or functionality) missing

### ISSUE THREAD

**Issue by KuenzelIT** [ohnotnow/cronmon#5]
Hey, when I go to /admin/job or /admin/team and I see all Jobs/Teams, there is no button to create a new job or team. There is a button in the overview to create a new job and a button under my account for creating a new team. Are the other buttons just missing?

**Comment by ohnotnow** [comment]
Do you mean you want the new job/team buttons to appear on the admin pages as well?  I think I didn't include them originally as I just assumed when you were in the admin section you were more looking at the overview of things rather than creating things.  I guess I can add the buttons to the admin pages too next time I'm working on the code though.

**Comment by KuenzelIT** [comment]
Hey,

you're right, I accidently meant the admin section, since I was logged in as an admin. I more or less had only an enterprise view in mind without jobs being strictly connected to users. Maybe I have to read the docs more first or try it out some more.

Yeah, but still, as an admin you should probably be able to create jobs and teams easily. I don't know about the consequences though.

Thanks for the quick response!

**Comment by ohnotnow** [comment]
Closing this for now - if I add the buttons to the admin page I'll ping you :-)
